# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Frontend
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/system/theme-override.js
