# Animated icons for default Home Assistant weather card
#
# Creator: Anton Averkiev - @wowgamr
# Repo: https://github.com/wowgamr/animated-weather-card

Animated Weather Card:
    weather-icon-clear-night: url("/hacsfiles/animated-weather-card/icons/clear-night.svg")
    weather-icon-cloudy: url("/hacsfiles/animated-weather-card/icons/cloudy.svg")
    weather-icon-fog: url("/hacsfiles/animated-weather-card/icons/fog.svg")
    weather-icon-lightning: url("/hacsfiles/animated-weather-card/icons/lightning.svg")
    weather-icon-lightning-rainy: url("/hacsfiles/animated-weather-card/icons/lightning.svg")
    weather-icon-partlycloudy: url("/hacsfiles/animated-weather-card/icons/partlycloudy.svg")
    weather-icon-pouring: url("/hacsfiles/animated-weather-card/icons/pouring.svg")
    weather-icon-rainy: url("/hacsfiles/animated-weather-card/icons/rainy.svg")
    weather-icon-hail: url("/hacsfiles/animated-weather-card/icons/hail.svg")
    weather-icon-snowy: url("/hacsfiles/animated-weather-card/icons/snowy.svg")
    weather-icon-snowy-rainy: url("/hacsfiles/animated-weather-card/icons/hail.svg")
    weather-icon-sunny: url("/hacsfiles/animated-weather-card/icons/sunny.svg")
    weather-icon-windy: url("/hacsfiles/animated-weather-card/icons/cloudy.svg")
    weather-icon-windy-variant: url("/hacsfiles/animated-weather-card/icons/partlycloudy.svg")
    weather-icon-exceptional: url("/hacsfiles/animated-weather-card/icons/exceptional.svg")